2015/03/31 01:40:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Gii".' in Q:\home\test1.ru\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Q:\home\test1.ru\www\framework\web\CWebApplication.php(141): CWebApplication->runController('Gii')
#1 Q:\home\test1.ru\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Q:\home\test1.ru\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=Gii
---
2015/03/31 01:40:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Q:\home\test1.ru\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Q:\home\test1.ru\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Q:\home\test1.ru\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Q:\home\test1.ru\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=gii
---
2015/03/31 01:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Q:\home\test1.ru\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Q:\home\test1.ru\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Q:\home\test1.ru\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Q:\home\test1.ru\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=gii
---
2015/03/31 01:46:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in Q:\home\test1.ru\www\framework\db\CDbConnection.php:399
Stack trace:
#0 Q:\home\test1.ru\www\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 Q:\home\test1.ru\www\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 Q:\home\test1.ru\www\framework\base\CModule.php(394): CDbConnection->init()
#3 Q:\home\test1.ru\www\framework\base\CModule.php(103): CModule->getComponent('db')
#4 Q:\home\test1.ru\www\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 Q:\home\test1.ru\www\framework\web\CFormModel.php(39): ModelCode->init()
#6 Q:\home\test1.ru\www\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 Q:\home\test1.ru\www\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 Q:\home\test1.ru\www\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 Q:\home\test1.ru\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 Q:\home\test1.ru\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 Q:\home\test1.ru\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 Q:\home\test1.ru\www\framework\web\CWebApplication.php(282): CController->run('index')
#13 Q:\home\test1.ru\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 Q:\home\test1.ru\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 Q:\home\test1.ru\www\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://test1.ru/index.php?r=gii/default/index
---
2015/04/01 00:52:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "tbluser".' in Q:\home\test1.ru\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Q:\home\test1.ru\www\framework\web\CWebApplication.php(141): CWebApplication->runController('tbluser')
#1 Q:\home\test1.ru\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Q:\home\test1.ru\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=tbluser
---
